spire-server:
  dataStore:
    sql:
      databaseType: postgres
      databaseName: spire-server
      host: postgresql.postgresql
      port: 5432
      username: spire
      password: sp1ff3Test
      options:
        - sslmode: disable
