# Role to be able to manage cert requests with Cert-Manager
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spiffe-oidc-discovery-provider.fullname" . }}-test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiffe-oidc-discovery-provider.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
rules:
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spiffe-oidc-discovery-provider.fullname" . }}-test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiffe-oidc-discovery-provider.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
subjects:
  - kind: ServiceAccount
    name: {{ include "spiffe-oidc-discovery-provider.serviceAccountName" . }}-test
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spiffe-oidc-discovery-provider.fullname" . }}-test
  apiGroup: rbac.authorization.k8s.io
---
